/**
 * \file IfxGeth_Eth_Phy_Dp83825i.c
 * \brief Source file of ETHERNET PHY DP83825I communication
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include "../Phy_Dp83825i/IfxGeth_Phy_Dp83825i.h"

/******************************************************************************/
/*----------------------------------Macros------------------------------------*/
/******************************************************************************/

#define IFXGETH_PHY_DP83825I_MDIO_BMCR     0x00

#define IFXGETH_PHY_DP83825I_MDIO_BMSR     0x01

#define IFXGETH_PHY_DP83825I_MDIO_PHYIDR1  0x02

#define IFXGETH_PHY_DP83825I_MDIO_PHYIDR2  0x03

#define IFXGETH_PHY_DP83825I_MDIO_ANAR     0x04

#define IFXGETH_PHY_DP83825I_MDIO_ALNPAR   0x05

#define IFXGETH_PHY_DP83825I_MDIO_ANER     0x06

#define IFXGETH_PHY_DP83825I_MDIO_PHYSTS   0x10

#define IFXGETH_PHY_DP83825I_MDIO_TIMEOUT  (100000u)
#define IFXGETH_PHY_DP83825I_RESET_TIMEOUT (10000u)
#define IFXGETH_PHY_DP83825I_PHY_ID_INVALID_LOW  (0x0000u)
#define IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH (0xFFFFu)

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

volatile uint32 Ethernet_Phy_Id1;
volatile uint32 Ethernet_Phy_Id2;
volatile boolean Phy_IdRed = FALSE;

#if CPU_WHICH_SERVICE_ETHERNET == 0
    #if defined(__GNUC__)
    #pragma section ".text_cpu0" ax
    #pragma section ".bss_cpu0" awc0
    #endif
    #if defined(__TASKING__)
    #pragma section code    "text_cpu0"
    #pragma section farbss  "bss_cpu0"
    #pragma section fardata "data_cpu0"
    #endif
    #if defined(__DCC__)
    #pragma section CODE ".text_cpu0"
    #pragma section DATA ".data_cpu0" ".bss_cpu0" far-absolute RW
    #endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu0"
    #pragma ghs section bss= ".bss_cpu0"
    #pragma ghs section data=".data_cpu0"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 1) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
    #if defined(__GNUC__)
    #pragma section ".text_cpu1" ax
    #pragma section ".bss_cpu1" awc1
    #endif
    #if defined(__TASKING__)
    #pragma section code    "text_cpu1"
    #pragma section farbss  "bss_cpu1"
    #pragma section fardata "data_cpu1"
    #endif
    #if defined(__DCC__)
    #pragma section CODE ".text_cpu1"
    #pragma section DATA ".data_cpu1" ".bss_cpu1" far-absolute RW
    #endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu1"
    #pragma ghs section bss= ".bss_cpu1"
    #pragma ghs section data=".data_cpu1"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 2) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
    #if defined(__GNUC__)
    #pragma section ".text_cpu2" ax
    #pragma section ".bss_cpu2" awc2
    #endif
    #if defined(__TASKING__)
    #pragma section code    "text_cpu2"
    #pragma section farbss  "bss_cpu2"
    #pragma section fardata "data_cpu2"
    #endif
    #if defined(__DCC__)
    #pragma section CODE ".text_cpu2"
    #pragma section DATA ".data_cpu2" ".bss_cpu2" far-absolute RW
    #endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu2"
    #pragma ghs section bss= ".bss_cpu2"
    #pragma ghs section data=".data_cpu2"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 3) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
	#if defined(__GNUC__)
    #pragma section ".text_cpu3" ax
	#pragma section ".bss_cpu3" awc3
	#endif
	#if defined(__TASKING__)
    #pragma section code    "text_cpu3"
    #pragma section farbss  "bss_cpu3"
    #pragma section fardata "data_cpu3"
	#endif
	#if defined(__DCC__)
    #pragma section CODE ".text_cpu3"
	#pragma section DATA ".data_cpu3" ".bss_cpu3" far-absolute RW
	#endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu3"
    #pragma ghs section bss= ".bss_cpu3"
    #pragma ghs section data=".data_cpu3"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 4) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
	#if defined(__GNUC__)
    #pragma section ".text_cpu4" ax
	#pragma section ".bss_cpu4" awc4
	#endif
	#if defined(__TASKING__)
    #pragma section code    "text_cpu4"
    #pragma section farbss  "bss_cpu4"
    #pragma section fardata "data_cpu4"
	#endif
	#if defined(__DCC__)
    #pragma section CODE ".text_cpu4"
	#pragma section DATA ".data_cpu4" ".bss_cpu4" far-absolute RW
	#endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu4"
    #pragma ghs section bss= ".bss_cpu4"
    #pragma ghs section data=".data_cpu4"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 5) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
	#if defined(__GNUC__)
    #pragma section ".text_cpu5" ax
	#pragma section ".bss_cpu5" awc5
	#endif
	#if defined(__TASKING__)
    #pragma section code    "text_cpu5"
    #pragma section farbss  "bss_cpu5"
    #pragma section fardata "data_cpu5"
	#endif
	#if defined(__DCC__)
    #pragma section CODE ".text_cpu5"
	#pragma section DATA ".data_cpu5" ".bss_cpu5" far-absolute RW
	#endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu5"
    #pragma ghs section bss= ".bss_cpu5"
    #pragma ghs section data=".data_cpu5"
    #endif
#else
#error "Set CPU_WHICH_SERVICE_ETHERNET to a valid value!"
#endif

/******************************************************************************/
/*-----------------------Exported Variables/Constants-------------------------*/
/******************************************************************************/

uint32 IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone = 0;

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/
#if defined(__GNUC__)
    #pragma section // end bss section
#endif

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/
static uint32 IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready(void);
static uint32 IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(uint32 layeraddr, uint32 regaddr, uint32 *pdata);
static uint32 IfxGeth_Eth_Phy_Dp83825i_write_mdio_reg_checked(uint32 layeraddr, uint32 regaddr, uint32 data);
static uint32 IfxGeth_Eth_Phy_Dp83825i_read_phy_id(void);
static uint32 IfxGeth_Eth_Phy_Dp83825i_soft_reset(void);
static uint32 IfxGeth_Eth_Phy_Dp83825i_restart_autoneg(void);

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/
static uint32 IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready(void)
{
    uint32 timeout = IFXGETH_PHY_DP83825I_MDIO_TIMEOUT;

    while (GETH_MAC_MDIO_ADDRESS.B.GB != 0u)
    {
        if (timeout == 0u)
        {
            return 0u;
        }

        timeout--;
    }

    return 1u;
}

static uint32 IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(uint32 layeraddr, uint32 regaddr, uint32 *pdata)
{
    if (pdata == 0)
    {
        return 0u;
    }

    if (IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready() == 0u)
    {
        *pdata = IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH;
        return 0u;
    }

    GETH_MAC_MDIO_ADDRESS.U = (layeraddr << 21) | (regaddr << 16) | (0 << 8) | (3 << 2) | (1 << 0);

    if (IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready() == 0u)
    {
        *pdata = IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH;
        return 0u;
    }

    *pdata = GETH_MAC_MDIO_DATA.U & 0xFFFFu;

    return 1u;
}

static uint32 IfxGeth_Eth_Phy_Dp83825i_write_mdio_reg_checked(uint32 layeraddr, uint32 regaddr, uint32 data)
{
    if (IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready() == 0u)
    {
        return 0u;
    }

    GETH_MAC_MDIO_DATA.U = data;
    GETH_MAC_MDIO_ADDRESS.U = (layeraddr << 21) | (regaddr << 16) | (0 << 8) |  (1 << 2) | (1 << 0);

    return IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready();
}

static uint32 IfxGeth_Eth_Phy_Dp83825i_read_phy_id(void)
{
    uint32 phy_id1;
    uint32 phy_id2;

    if (IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_PHYIDR1, &phy_id1) == 0u)
    {
        Ethernet_Phy_Id1 = IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH;
        Ethernet_Phy_Id2 = IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH;
        Phy_IdRed = TRUE;
        return 0u;
    }

    if (IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_PHYIDR2, &phy_id2) == 0u)
    {
        Ethernet_Phy_Id1 = phy_id1;
        Ethernet_Phy_Id2 = IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH;
        Phy_IdRed = TRUE;
        return 0u;
    }

    Ethernet_Phy_Id1 = phy_id1;
    Ethernet_Phy_Id2 = phy_id2;
    Phy_IdRed = TRUE;

    if ((phy_id1 == IFXGETH_PHY_DP83825I_PHY_ID_INVALID_LOW) ||
        (phy_id1 == IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH) ||
        (phy_id2 == IFXGETH_PHY_DP83825I_PHY_ID_INVALID_LOW) ||
        (phy_id2 == IFXGETH_PHY_DP83825I_PHY_ID_INVALID_HIGH))
    {
        return 0u;
    }

    return 1u;
}

static uint32 IfxGeth_Eth_Phy_Dp83825i_soft_reset(void)
{
    uint32 value;
    uint32 timeout;

    if (IfxGeth_Eth_Phy_Dp83825i_write_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_BMCR, 0x8000u) == 0u)
    {
        return 0u;
    }

    for (timeout = IFXGETH_PHY_DP83825I_RESET_TIMEOUT; timeout > 0u; timeout--)
    {
        if (IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_BMCR, &value) == 0u)
        {
            return 0u;
        }

        if ((value & 0x8000u) == 0u)
        {
            return 1u;
        }
    }

    return 0u;
}

static uint32 IfxGeth_Eth_Phy_Dp83825i_restart_autoneg(void)
{
    return IfxGeth_Eth_Phy_Dp83825i_write_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_BMCR, 0x1200u);
}

void IfxGet_Eth_Phy_Dp83825i_reset(void) {

    /* now we check the phy to know the board version */
    if (IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready() == 0u)
    {
        Ethernet_Phy_Id1 = 0u;
        Ethernet_Phy_Id2 = 0u;
        Phy_IdRed = TRUE;
        return;
    }

    // reset PHY
    // first we test to readout the reset bit to avoid timing issues (phy not yet ready)
    uint32 value;
    uint32 uiTimeout = 2000;
    do
    {
        GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) | (3 << 2) | (1 << 0);
        if (IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready() == 0u)
        {
            Ethernet_Phy_Id1 = 0u;
            Ethernet_Phy_Id2 = 0u;
            Phy_IdRed = TRUE;
            return;
        }
        value = GETH_MAC_MDIO_DATA.U;
    } while ((value & 0x8000) && (uiTimeout--));  // wait for reset to finish

    if (uiTimeout != 0xFFFFFFFF)
    {
        // put data (reset the phy)
        GETH_MAC_MDIO_DATA.U = 0x8000;
        GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) |  (1 << 2) | (1 << 0);
        if (IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready() == 0u)
        {
            Ethernet_Phy_Id1 = 0u;
            Ethernet_Phy_Id2 = 0u;
            Phy_IdRed = TRUE;
            return;
        }

        uiTimeout = 2000;

        do
        {
            GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) | (3 << 2) | (1 << 0);
            if (IfxGeth_Eth_Phy_Dp83825i_wait_mdio_ready() == 0u)
            {
                Ethernet_Phy_Id1 = 0u;
                Ethernet_Phy_Id2 = 0u;
                Phy_IdRed = TRUE;
                return;
            }
            value = GETH_MAC_MDIO_DATA.U;
        } while ((value & 0x8000) && (uiTimeout--));  // wait for reset to finish

        if (uiTimeout == 0xFFFFFFFFu)
        {
            Ethernet_Phy_Id1 = 0u;
            Ethernet_Phy_Id2 = 0u;
            Phy_IdRed = TRUE;
            return;
        }

        // get ID
        (void)IfxGeth_Eth_Phy_Dp83825i_read_phy_id();
    }
    else
    {
        Ethernet_Phy_Id1 = 0;
    }
    Phy_IdRed = TRUE;
}

uint32 IfxGeth_Eth_Phy_Dp83825i_init(void)
{
    IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone = 0u;

    if (IfxGeth_Eth_Phy_Dp83825i_soft_reset() == 0u)
    {
        return 0u;
    }

    if (IfxGeth_Eth_Phy_Dp83825i_read_phy_id() == 0u)
    {
        return 0u;
    }

    if (IfxGeth_Eth_Phy_Dp83825i_restart_autoneg() == 0u)
    {
        return 0u;
    }

    // done
    IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone = 1;

    return 1;
}

uint32 IfxGeth_Eth_Phy_Dp83825i_recover(void)
{
    if (IfxGeth_Eth_Phy_Dp83825i_read_phy_id() == 0u)
    {
        return 0u;
    }

    if (IfxGeth_Eth_Phy_Dp83825i_soft_reset() == 0u)
    {
        return 0u;
    }

    if (IfxGeth_Eth_Phy_Dp83825i_restart_autoneg() == 0u)
    {
        return 0u;
    }

    IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone = 1u;

    return 1u;
}



uint32 IfxGeth_Eth_Phy_Dp83825i_link_status(void)
{
	Ifx_GETH_MAC_PHYIF_CONTROL_STATUS link_status;
	uint32 value;
	link_status.U = 0;

    if (IfxGeth_Eth_Phy_Dp83825i_iPhyInitDone)
    {
        // We read the phy status register
        if (IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_PHYSTS, &value) == 0u)
        {
            return link_status.U;
        }

        if (!(value & 0x2)) link_status.B.LNKSPEED = 1;
        if (value & 0x4) link_status.B.LNKMOD = 1;

        if (IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_BMSR, &value) == 0u)
        {
            return link_status.U;
        }

        if (IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(0, IFXGETH_PHY_DP83825I_MDIO_BMSR, &value) == 0u)
        {
            return link_status.U;
        }

        if (value & 0x4) link_status.B.LNKSTS = 1;
    }

    return link_status.U;
}

void IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 *pdata)
{
    (void)IfxGeth_Eth_Phy_Dp83825i_read_mdio_reg_checked(layeraddr, regaddr, pdata);
}


void IfxGeth_Eth_Phy_Dp83825i_write_mdio_reg(uint32 layeraddr, uint32 regaddr, uint32 data)
{
    (void)IfxGeth_Eth_Phy_Dp83825i_write_mdio_reg_checked(layeraddr, regaddr, data);
}

#if defined(__GNUC__)
#pragma section // end text section
#endif
#if defined(__TASKING__)
#pragma section code restore
#pragma section fardata restore
#pragma section farbss restore
#endif
#if defined(__DCC__)
#pragma section CODE
#pragma section DATA RW
#endif
#if defined(__ghs__)
#pragma ghs section text=default
#pragma ghs section data=default
#pragma ghs section bss=default
#endif
